<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <OptionStrict>On</OptionStrict>
    <RootNamespace>BatchToApp.RegressionTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../Obfuscator.vb" Link="Obfuscator.vb" />
  </ItemGroup>
</Project>
